version: '3.8'

services:
  backend:
    # build: .
    image: luisedu/app-panel-api:latest
    container_name: panel_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
